import type { Quotation } from './types';

export const initialData: Quotation[] = [
  {
    id: 1,
    entity: 'UAE',
    supplierName: 'SHKE',
    supplierPO: 'P227998',
    poValue: 567309.44,
    origin: 'Shenzen',
    destination: 'Jabel Ali',
    mode: 'SEA FCL',
    size: '1 x 40ft HQ + 1 X 20ft',
    transitTime: '',
    incoterms: 'Exworks',
    quotes: [
      { forwarder: 'BDP', quotedAmount: 66740.00 },
      { forwarder: 'Expeditors', quotedAmount: 60229.00 },
    ],
    awardedTo: 'Expeditors',
    remarks: 'Collected ETA 07-07-2026',
    percentage: 10.62,
    etd: '',
    eta: '2026-07-07',
    status: 'Delivered',
    savings: 0,
  },
  {
    id: 2,
    entity: 'UAE',
    supplierName: 'Legrand 1st Batch',
    supplierPO: 'P165602',
    poValue: 286184.34,
    origin: 'Netherlands',
    destination: 'Jabel Ali',
    mode: 'SEA FCL',
    size: '2 x 40ft HQ',
    transitTime: '',
    incoterms: 'Exworks',
    quotes: [
      { forwarder: 'BDP', quotedAmount: 63200.00 },
      { forwarder: 'Expeditors', quotedAmount: 51929.15 },
    ],
    awardedTo: 'Expeditors',
    remarks: 'ETD 27-06-2026 ETA 07-08-2026',
    percentage: 18.15,
    etd: '2026-06-27',
    eta: '2026-08-07',
    status: 'In Transit',
    savings: 11270.85,
  },
  {
    id: 3,
    entity: 'UAE',
    supplierName: 'Legrand 2nd Batch',
    supplierPO: 'P165602',
    poValue: 293625.92,
    origin: 'Netherlands',
    destination: 'Jabel Ali',
    mode: 'SEA FCL',
    size: '2 x 40ft HQ',
    transitTime: '50 to 60 Days',
    incoterms: 'Exworks',
    quotes: [
      { forwarder: 'BDP', quotedAmount: 63000.00 },
      { forwarder: 'Expeditors', quotedAmount: 52443.30 },
    ],
    awardedTo: 'Expeditors',
    remarks: '',
    percentage: 17.86,
    etd: '',
    eta: '',
    status: 'Assign to forwarder',
    savings: 10556.70,
  },
  {
    id: 4,
    entity: 'UAE',
    supplierName: 'Shenzen O Cable',
    supplierPO: 'P228028',
    poValue: 18729.75,
    origin: 'Shenzen',
    destination: 'Jabel Ali',
    mode: 'SEA LCL',
    size: '12 Ctns',
    transitTime: '35 Days',
    incoterms: 'Exworks',
    quotes: [
      { forwarder: 'BDP', quotedAmount: 3395.00 },
      { forwarder: 'Expeditors', quotedAmount: 2995.00 },
    ],
    awardedTo: '',
    remarks: '',
    percentage: 15.99,
    etd: '',
    eta: '',
    status: 'Sent for quotation',
    savings: 0,
  },
  {
    id: 5,
    entity: 'UAE',
    supplierName: 'R&M',
    supplierPO: 'P228038',
    poValue: 11593.45818,
    origin: 'Jafza',
    destination: 'Dubai',
    mode: 'Road',
    size: '2 Pallets',
    transitTime: '30 to 35 Days',
    incoterms: 'Exworks',
    quotes: [
      { forwarder: 'BDP', quotedAmount: 1013.50 },
      { forwarder: 'Expeditors', quotedAmount: 973.50 },
    ],
    awardedTo: 'Expeditors',
    remarks: '',
    percentage: 8.40,
    etd: '',
    eta: '',
    status: 'Under Clearence',
    savings: 40.00,
  },
  {
    id: 6,
    entity: 'Qatar',
    supplierName: 'Linkz',
    supplierPO: 'P181524',
    poValue: 420809.74,
    origin: 'Shanghai',
    destination: 'Doha',
    mode: 'SEA FCL',
    size: '1 x 20ft + 2 x 40ft',
    transitTime: '',
    incoterms: 'FOB',
    quotes: [
      { forwarder: 'BDP', quotedAmount: 81850.00 },
      { forwarder: 'ECU', quotedAmount: 83425.00 },
    ],
    awardedTo: '',
    remarks: '',
    percentage: 19.82,
    etd: '',
    eta: '',
    status: 'Sent for quotation',
    savings: 0,
  },
  {
    id: 7,
    entity: 'Qatar',
    supplierName: 'Planet',
    supplierPO: 'P181727',
    poValue: 146973.45,
    origin: 'Taiwan',
    destination: 'Doha',
    mode: 'Air',
    size: '338 Kg',
    transitTime: '',
    incoterms: 'FOB',
    quotes: [
      { forwarder: 'BDP', quotedAmount: 7350.00 },
      { forwarder: 'ECU', quotedAmount: 7200.00 },
    ],
    awardedTo: '',
    remarks: '',
    percentage: 4.90,
    etd: '',
    eta: '',
    status: 'Arrived Awaiting clearence',
    savings: 150.00,
  },
];
