export interface Country {
  name: string;
  cities: string[];
}

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', cities: ['Kabul', 'Herat', 'Mazar-i-Sharif', 'Kandahar'] },
  { name: 'Albania', cities: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'] },
  { name: 'Algeria', cities: ['Algiers', 'Oran', 'Constantine', 'Annaba'] },
  { name: 'Andorra', cities: ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp'] },
  { name: 'Angola', cities: ['Luanda', 'Huambo', 'Lobito', 'Benguela'] },
  { name: 'Argentina', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'] },
  { name: 'Armenia', cities: ['Yerevan', 'Gyumri', 'Vanadzor'] },
  { name: 'Australia', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast'] },
  { name: 'Austria', cities: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'] },
  { name: 'Azerbaijan', cities: ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir'] },
  { name: 'Bahamas', cities: ['Nassau', 'Freeport'] },
  { name: 'Bahrain', cities: ['Manama', 'Muharraq', 'Riffa'] },
  { name: 'Bangladesh', cities: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet'] },
  { name: 'Barbados', cities: ['Bridgetown', 'Speightstown'] },
  { name: 'Belarus', cities: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk'] },
  { name: 'Belgium', cities: ['Brussels', 'Antwerp', 'Ghent', 'Bruges', 'Liège', 'Charleroi', 'Namur', 'Leuven', 'Kortrijk', 'Mons'] },
  { name: 'Belize', cities: ['Belmopan', 'Belize City'] },
  { name: 'Benin', cities: ['Porto-Novo', 'Cotonou'] },
  { name: 'Bhutan', cities: ['Thimphu', 'Phuntsholing'] },
  { name: 'Bolivia', cities: ['Sucre', 'La Paz', 'Santa Cruz', 'Cochabamba'] },
  { name: 'Bosnia and Herzegovina', cities: ['Sarajevo', 'Banja Luka', 'Tuzla'] },
  { name: 'Botswana', cities: ['Gaborone', 'Francistown', 'Maun'] },
  { name: 'Brazil', cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba'] },
  { name: 'Brunei', cities: ['Bandar Seri Begawan', 'Miri'] },
  { name: 'Bulgaria', cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas'] },
  { name: 'Burkina Faso', cities: ['Ouagadougou', 'Bobo-Dioulasso'] },
  { name: 'Burundi', cities: ['Gitega', 'Bujumbura'] },
  { name: 'Cambodia', cities: ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'] },
  { name: 'Cameroon', cities: ['Yaoundé', 'Douala', 'Bamenda'] },
  { name: 'Canada', cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg'] },
  { name: 'Central African Republic', cities: ['Bangui', 'Bimbo'] },
  { name: 'Chad', cities: ['N\'Djamena', 'Moundou'] },
  { name: 'Chile', cities: ['Santiago', 'Valparaíso', 'Concepción', 'Antofagasta'] },
  { name: 'China', cities: ['Shanghai', 'Beijing', 'Shenzhen', 'Guangzhou', 'Chengdu', 'Hong Kong', 'Ningbo', 'Qingdao', 'Tianjin', 'Dalian', 'Xiamen', 'Chongqing', 'Wuhan', 'Hangzhou', 'Suzhou'] },
  { name: 'Colombia', cities: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'] },
  { name: 'Comoros', cities: ['Moroni', 'Mutsamudu'] },
  { name: 'Congo (DRC)', cities: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi'] },
  { name: 'Congo (Republic)', cities: ['Brazzaville', 'Pointe-Noire'] },
  { name: 'Costa Rica', cities: ['San José', 'Limón', 'Puerto Limón'] },
  { name: 'Croatia', cities: ['Zagreb', 'Split', 'Rijeka', 'Dubrovnik'] },
  { name: 'Cuba', cities: ['Havana', 'Santiago de Cuba', 'Camagüey'] },
  { name: 'Cyprus', cities: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'] },
  { name: 'Czech Republic', cities: ['Prague', 'Brno', 'Ostrava', 'Plzen'] },
  { name: 'Denmark', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'] },
  { name: 'Djibouti', cities: ['Djibouti City'] },
  { name: 'Dominican Republic', cities: ['Santo Domingo', 'Santiago de los Caballeros', 'La Romana'] },
  { name: 'Ecuador', cities: ['Quito', 'Guayaquil', 'Cuenca'] },
  { name: 'Egypt', cities: ['Cairo', 'Alexandria', 'Port Said', 'Suez', 'Ismailia'] },
  { name: 'El Salvador', cities: ['San Salvador', 'Santa Ana', 'San Miguel'] },
  { name: 'Equatorial Guinea', cities: ['Malabo', 'Bata'] },
  { name: 'Eritrea', cities: ['Asmara', 'Keren'] },
  { name: 'Estonia', cities: ['Tallinn', 'Tartu', 'Narva'] },
  { name: 'Eswatini', cities: ['Mbabane', 'Manzini'] },
  { name: 'Ethiopia', cities: ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Hawassa'] },
  { name: 'Fiji', cities: ['Suva', 'Nadi', 'Lautoka'] },
  { name: 'Finland', cities: ['Helsinki', 'Espoo', 'Tampere', 'Turku', 'Oulu'] },
  { name: 'France', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Bordeaux', 'Lille', 'Le Havre', 'Dunkirk', 'Rouen', 'Reims', 'Saint-Étienne', 'Toulon'] },
  { name: 'Gabon', cities: ['Libreville', 'Port-Gentil', 'Franceville'] },
  { name: 'Gambia', cities: ['Banjul', 'Serekunda'] },
  { name: 'Georgia', cities: ['Tbilisi', 'Batumi', 'Kutaisi'] },
  { name: 'Germany', cities: ['Berlin', 'Hamburg', 'Munich', 'Frankfurt', 'Cologne', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dortmund', 'Essen', 'Alsdorf', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld', 'Bonn', 'Münster', 'Karlsruhe', 'Mannheim', 'Augsburg', 'Nuremberg', 'Wiesbaden', 'Rostock', 'Kiel', 'Hannover', 'Bremen', 'Dresden', 'Heidelberg', 'Ulm', 'Gelsenkirchen'] },
  { name: 'Ghana', cities: ['Accra', 'Kumasi', 'Tamale', 'Takoradi'] },
  { name: 'Greece', cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa'] },
  { name: 'Guatemala', cities: ['Guatemala City', 'Quetzaltenango', 'Escuintla'] },
  { name: 'Guinea', cities: ['Conakry', 'Kankan', 'Nzérékoré'] },
  { name: 'Guinea-Bissau', cities: ['Bissau', 'Bafatá'] },
  { name: 'Guyana', cities: ['Georgetown', 'Linden'] },
  { name: 'Haiti', cities: ['Port-au-Prince', 'Cap-Haïtien', 'Gonaïves'] },
  { name: 'Honduras', cities: ['Tegucigalpa', 'San Pedro Sula', 'Choloma'] },
  { name: 'Hungary', cities: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs'] },
  { name: 'Iceland', cities: ['Reykjavik', 'Kópavogur', 'Hafnarfjörður'] },
  { name: 'India', cities: ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Kolkata', 'Hyderabad', 'Ahmedabad', 'Pune', 'Jaipur', 'Lucknow', 'Kochi', 'Tiruchirappalli'] },
  { name: 'Indonesia', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang', 'Tangerang'] },
  { name: 'Iran', cities: ['Tehran', 'Isfahan', 'Mashhad', 'Karaj', 'Tabriz', 'Shiraz'] },
  { name: 'Iraq', cities: ['Baghdad', 'Basra', 'Erbil', 'Mosul', 'Najaf'] },
  { name: 'Ireland', cities: ['Dublin', 'Cork', 'Galway', 'Limerick'] },
  { name: 'Israel', cities: ['Jerusalem', 'Tel Aviv', 'Haifa', 'Beer Sheva'] },
  { name: 'Italy', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Venice', 'Trieste', 'Livorno', 'La Spezia', 'Genova', 'Catania', 'Bari', 'Verona', 'Padua'] },
  { name: 'Ivory Coast', cities: ['Yamoussoukro', 'Abidjan', 'Bouaké'] },
  { name: 'Jamaica', cities: ['Kingston', 'Montego Bay', 'Spanish Town'] },
  { name: 'Japan', cities: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kyoto'] },
  { name: 'Jordan', cities: ['Amman', 'Zarqa', 'Irbid', 'Aqaba'] },
  { name: 'Kazakhstan', cities: ['Astana', 'Almaty', 'Shymkent', 'Aktobe'] },
  { name: 'Kenya', cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'] },
  { name: 'Kuwait', cities: ['Kuwait City', 'Hawalli', 'Salmiya', 'Al Ahmadi'] },
  { name: 'Kyrgyzstan', cities: ['Bishkek', 'Osh', 'Jalal-Abad'] },
  { name: 'Laos', cities: ['Vientiane', 'Luang Prabang', 'Savannakhet'] },
  { name: 'Latvia', cities: ['Riga', 'Daugavpils', 'Liepāja'] },
  { name: 'Lebanon', cities: ['Beirut', 'Tripoli', 'Sidon', 'Tyre'] },
  { name: 'Lesotho', cities: ['Maseru', 'Teyateyaneng'] },
  { name: 'Liberia', cities: ['Monrovia', 'Gbarnga'] },
  { name: 'Libya', cities: ['Tripoli', 'Benghazi', 'Misrata', 'Tobruk'] },
  { name: 'Lithuania', cities: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai'] },
  { name: 'Luxembourg', cities: ['Luxembourg City', 'Esch-sur-Alzette'] },
  { name: 'Madagascar', cities: ['Antananarivo', 'Toamasina', 'Antsirabe'] },
  { name: 'Malawi', cities: ['Lilongwe', 'Blantyre', 'Mzuzu'] },
  { name: 'Malaysia', cities: ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Ipoh', 'Kota Kinabalu', 'Kuching', 'Malacca City'] },
  { name: 'Maldives', cities: ['Malé'] },
  { name: 'Mali', cities: ['Bamako', 'Sikasso', 'Mopti'] },
  { name: 'Malta', cities: ['Valletta', 'Birkirkara', 'Mosta'] },
  { name: 'Mauritania', cities: ['Nouakchott', 'Nouadhibou'] },
  { name: 'Mauritius', cities: ['Port Louis', 'Beau Bassin-Rose Hill', 'Curepipe'] },
  { name: 'Mexico', cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Cancún', 'Puebla', 'Tijuana', 'León', 'Mérida'] },
  { name: 'Moldova', cities: ['Chișinău', 'Tiraspol', 'Bălți'] },
  { name: 'Monaco', cities: ['Monaco'] },
  { name: 'Mongolia', cities: ['Ulaanbaatar', 'Erdenet', 'Darkhan'] },
  { name: 'Montenegro', cities: ['Podgorica', 'Nikšić', 'Herceg Novi'] },
  { name: 'Morocco', cities: ['Casablanca', 'Rabat', 'Fez', 'Marrakech', 'Tangier', 'Agadir'] },
  { name: 'Mozambique', cities: ['Maputo', 'Beira', 'Nampula'] },
  { name: 'Myanmar', cities: ['Naypyidaw', 'Yangon', 'Mandalay'] },
  { name: 'Namibia', cities: ['Windhoek', 'Walvis Bay', 'Swakopmund'] },
  { name: 'Nepal', cities: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar'] },
  { name: 'Netherlands', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen', 'Tilburg', 'Almere', 'Breda', 'Nijmegen', 'Apeldoorn', 'Arnhem', 'Zaandam', 'Venlo', 'Maastricht'] },
  { name: 'New Zealand', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga'] },
  { name: 'Nicaragua', cities: ['Managua', 'León', 'Masaya'] },
  { name: 'Niger', cities: ['Niamey', 'Zinder', 'Maradi'] },
  { name: 'Nigeria', cities: ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City', 'Kaduna'] },
  { name: 'North Korea', cities: ['Pyongyang', 'Hamhung', 'Chongjin'] },
  { name: 'North Macedonia', cities: ['Skopje', 'Bitola', 'Kumanovo'] },
  { name: 'Norway', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen'] },
  { name: 'Oman', cities: ['Muscat', 'Salalah', 'Sohar', 'Nizwa'] },
  { name: 'Pakistan', cities: ['Karachi', 'Lahore', 'Islamabad', 'Faisalabad', 'Rawalpindi', 'Multan', 'Peshawar'] },
  { name: 'Panama', cities: ['Panama City', 'Colón', 'David'] },
  { name: 'Papua New Guinea', cities: ['Port Moresby', 'Lae', 'Mount Hagen'] },
  { name: 'Paraguay', cities: ['Asunción', 'Ciudad del Este', 'San Lorenzo'] },
  { name: 'Peru', cities: ['Lima', 'Arequipa', 'Trujillo', 'Cusco', 'Chiclayo'] },
  { name: 'Philippines', cities: ['Manila', 'Quezon City', 'Davao City', 'Cebu City', 'Zamboanga City', 'Taguig', 'Antipolo'] },
  { name: 'Poland', cities: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin'] },
  { name: 'Portugal', cities: ['Lisbon', 'Porto', 'Faro', 'Braga', 'Coimbra'] },
  { name: 'Qatar', cities: ['Doha', 'Al Wakrah', 'Al Khor', 'Dukhan', 'Ras Laffan'] },
  { name: 'Romania', cities: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Brașov'] },
  { name: 'Russia', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Vladivostok'] },
  { name: 'Rwanda', cities: ['Kigali', 'Butare', 'Gisenyi'] },
  { name: 'Saudi Arabia', cities: ['Riyadh', 'Jeddah', 'Dammam', 'Mecca', 'Medina', 'Al Khobar', 'Jubail'] },
  { name: 'Senegal', cities: ['Dakar', 'Thiès', 'Saint-Louis'] },
  { name: 'Serbia', cities: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac'] },
  { name: 'Seychelles', cities: ['Victoria'] },
  { name: 'Sierra Leone', cities: ['Freetown', 'Bo'] },
  { name: 'Singapore', cities: ['Singapore'] },
  { name: 'Slovakia', cities: ['Bratislava', 'Košice', 'Prešov', 'Žilina'] },
  { name: 'Slovenia', cities: ['Ljubljana', 'Maribor', 'Celje', 'Kranj'] },
  { name: 'Somalia', cities: ['Mogadishu', 'Hargeisa', 'Kismayo'] },
  { name: 'South Africa', cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein'] },
  { name: 'South Korea', cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Ulsan'] },
  { name: 'South Sudan', cities: ['Juba', 'Malakal', 'Wau'] },
  { name: 'Spain', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Málaga', 'Bilbao', 'Zaragoza', 'Las Palmas', 'Alicante', 'Vigo', 'Gijón', 'Granada', 'Córdoba', 'Valladolid', 'Algeciras'] },
  { name: 'Sri Lanka', cities: ['Colombo', 'Sri Jayawardenepura Kotte', 'Galle', 'Kandy'] },
  { name: 'Sudan', cities: ['Khartoum', 'Omdurman', 'Port Sudan'] },
  { name: 'Suriname', cities: ['Paramaribo', 'Lelydorp'] },
  { name: 'Sweden', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Linköping'] },
  { name: 'Switzerland', cities: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne'] },
  { name: 'Syria', cities: ['Damascus', 'Aleppo', 'Homs', 'Latakia'] },
  { name: 'Taiwan', cities: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu'] },
  { name: 'Tajikistan', cities: ['Dushanbe', 'Khujand', 'Bokhtar'] },
  { name: 'Tanzania', cities: ['Dar es Salaam', 'Dodoma', 'Arusha', 'Zanzibar City'] },
  { name: 'Thailand', cities: ['Bangkok', 'Chiang Mai', 'Pattaya', 'Phuket', 'Nakhon Ratchasima', 'Hat Yai'] },
  { name: 'Timor-Leste', cities: ['Dili', 'Baucau'] },
  { name: 'Togo', cities: ['Lomé', 'Kara', 'Sokodé'] },
  { name: 'Trinidad and Tobago', cities: ['Port of Spain', 'San Fernando', 'Chaguanas'] },
  { name: 'Tunisia', cities: ['Tunis', 'Sfax', 'Sousse', 'Kairouan'] },
  { name: 'Turkey', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Trabzon'] },
  { name: 'Turkmenistan', cities: ['Ashgabat', 'Türkmenabat', 'Daşoguz'] },
  { name: 'Uganda', cities: ['Kampala', 'Gulu', 'Lira', 'Mbarara'] },
  { name: 'Ukraine', cities: ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Lviv', 'Zaporizhzhia'] },
  { name: 'United Arab Emirates', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'] },
  { name: 'United Kingdom', cities: ['London', 'Manchester', 'Birmingham', 'Liverpool', 'Leeds', 'Glasgow', 'Edinburgh', 'Bristol', 'Newcastle', 'Sheffield', 'Nottingham', 'Leicester', 'Coventry', 'Bradford', 'Cardiff', 'Belfast', 'Southampton', 'Dover', 'Felixstowe', 'Teesport'] },
  { name: 'United States', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Francisco', 'Seattle', 'Miami'] },
  { name: 'Uruguay', cities: ['Montevideo', 'Salto', 'Punta del Este'] },
  { name: 'Uzbekistan', cities: ['Tashkent', 'Samarkand', 'Bukhara', 'Namangan'] },
  { name: 'Vanuatu', cities: ['Port Vila', 'Luganville'] },
  { name: 'Venezuela', cities: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto'] },
  { name: 'Vietnam', cities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong', 'Can Tho', 'Bien Hoa'] },
  { name: 'Yemen', cities: ['Sana\'a', 'Aden', 'Taiz', 'Al Hudaydah'] },
  { name: 'Zambia', cities: ['Lusaka', 'Kitwe', 'Ndola', 'Livingstone'] },
  { name: 'Zimbabwe', cities: ['Harare', 'Bulawayo', 'Chitungwiza'] },
];

export const INCOTERMS_LIST = [
  { value: 'EXW', label: 'EXW - Ex Works' },
  { value: 'FCA', label: 'FCA - Free Carrier' },
  { value: 'FAS', label: 'FAS - Free Alongside Ship' },
  { value: 'FOB', label: 'FOB - Free On Board' },
  { value: 'CFR', label: 'CFR - Cost and Freight' },
  { value: 'CIF', label: 'CIF - Cost, Insurance & Freight' },
  { value: 'CPT', label: 'CPT - Carriage Paid To' },
  { value: 'CIP', label: 'CIP - Carriage and Insurance Paid To' },
  { value: 'DAP', label: 'DAP - Delivered at Place' },
  { value: 'DPU', label: 'DPU - Delivered at Place Unloaded' },
  { value: 'DDP', label: 'DDP - Delivered Duty Paid' },
] as const;

export const MODES_LIST = [
  { value: 'SEA FCL', label: 'Sea FCL (Full Container Load)' },
  { value: 'SEA LCL', label: 'Sea LCL (Less than Container Load)' },
  { value: 'Air', label: 'Air Freight' },
  { value: 'Road', label: 'Road / Trucking' },
  { value: 'Rail', label: 'Rail Freight' },
  { value: 'Multi-modal', label: 'Multi-modal / Intermodal' },
] as const;
